-- LevelOne PS Rental — database untuk GitHub Pages + Supabase
-- Jalankan seluruh file ini di Supabase SQL Editor.

create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('PS 3','PS 4')),
  station_number integer not null,
  status text not null default 'available' check (status in ('available','occupied','offline')),
  end_at timestamptz null,
  updated_at timestamptz not null default now(),
  unique(type, station_number)
);

insert into public.stations (type, station_number, status)
select 'PS 3', g, 'available' from generate_series(1,8) g
on conflict (type, station_number) do nothing;

insert into public.stations (type, station_number, status)
select 'PS 4', g, 'available' from generate_series(1,4) g
on conflict (type, station_number) do nothing;

alter table public.stations enable row level security;

-- Semua pengunjung boleh melihat status station.
drop policy if exists "Publik dapat melihat station" on public.stations;
create policy "Publik dapat melihat station"
on public.stations for select
using (true);

-- Hanya akun admin LevelOne yang boleh mengubah station.
drop policy if exists "Admin dapat mengubah station" on public.stations;
create policy "Admin dapat mengubah station"
on public.stations for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@levelone.local')
with check ((auth.jwt() ->> 'email') = 'admin@levelone.local');

-- Tidak ada insert/delete dari browser.
drop policy if exists "Tidak ada insert station dari browser" on public.stations;
drop policy if exists "Tidak ada delete station dari browser" on public.stations;

-- Realtime opsional, tetapi berguna agar perubahan admin cepat terlihat.
alter table public.stations replica identity full;

-- Izinkan role Data API membaca tabel sesuai RLS.
grant select on public.stations to anon;
grant select, update on public.stations to authenticated;
