-- LevelOne PS Rental — database untuk GitHub Pages + Supabase
-- Jalankan seluruh file ini di Supabase SQL Editor.

create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('PS 3','PS 4')),
  station_number integer not null,
  status text not null default 'available' check (status in ('available','occupied','offline')),
  end_at timestamptz null,
  updated_at timestamptz not null default now(),
  unique(type, station_number)
);

insert into public.stations (type, station_number, status)
select 'PS 3', g, 'available' from generate_series(1,8) g
on conflict (type, station_number) do nothing;

insert into public.stations (type, station_number, status)
select 'PS 4', g, 'available' from generate_series(1,4) g
on conflict (type, station_number) do nothing;

alter table public.stations enable row level security;

-- Semua pengunjung boleh melihat status station.
drop policy if exists "Publik dapat melihat station" on public.stations;
create policy "Publik dapat melihat station"
on public.stations for select
using (true);

-- Hanya akun admin LevelOne yang boleh mengubah station.
drop policy if exists "Admin dapat mengubah station" on public.stations;
create policy "Admin dapat mengubah station"
on public.stations for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@levelone.local')
with check ((auth.jwt() ->> 'email') = 'admin@levelone.local');

-- Tidak ada insert/delete dari browser.
drop policy if exists "Tidak ada insert station dari browser" on public.stations;
drop policy if exists "Tidak ada delete station dari browser" on public.stations;

-- Realtime opsional, tetapi berguna agar perubahan admin cepat terlihat.
alter table public.stations replica identity full;

-- Izinkan role Data API membaca tabel sesuai RLS.
grant select on public.stations to anon;
grant select, update on public.stations to authenticated;


-- ============================================================
-- REKAP PEMAKAIAN & PEMASUKAN HARIAN
-- Setiap kali admin menyimpan durasi bermain, transaksi dicatat.
-- Tarif: PS 3 = Rp3.000 / 30 menit; PS 4 = Rp5.000 / 30 menit.
-- ============================================================
create table if not exists public.play_sessions (
  id bigint generated by default as identity primary key,
  station_id bigint not null references public.stations(id) on delete cascade,
  type text not null check (type in ('PS 3','PS 4')),
  station_number integer not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz null,
  duration_minutes integer not null check (duration_minutes > 0 and duration_minutes % 30 = 0),
  price_per_30min integer not null check (price_per_30min in (3000,5000)),
  amount integer not null check (amount >= 0),
  updated_at timestamptz not null default now()
);

alter table public.play_sessions enable row level security;

drop policy if exists "Admin dapat melihat rekap" on public.play_sessions;
create policy "Admin dapat melihat rekap"
on public.play_sessions for select
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@levelone.local');

drop policy if exists "Admin dapat membuat rekap" on public.play_sessions;
create policy "Admin dapat membuat rekap"
on public.play_sessions for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'admin@levelone.local');

drop policy if exists "Admin dapat mengubah rekap" on public.play_sessions;
create policy "Admin dapat mengubah rekap"
on public.play_sessions for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@levelone.local')
with check ((auth.jwt() ->> 'email') = 'admin@levelone.local');

grant select, insert, update on public.play_sessions to authenticated;
grant usage, select on sequence public.play_sessions_id_seq to authenticated;
grant usage, select on sequence public.stations_id_seq to authenticated;

create index if not exists play_sessions_started_at_idx on public.play_sessions(started_at);
create index if not exists play_sessions_station_active_idx on public.play_sessions(station_id) where ended_at is null;


-- Jika tabel baru saja dibuat dan Supabase masih menampilkan "Could not find
-- the table 'public.play_sessions' in the schema cache", jalankan:
-- NOTIFY pgrst, 'reload schema';
